GET http://localhost:3000/

###
GET http://localhost:3000/categories

###
GET http://localhost:3000/categories/12

###
POST http://localhost:3000/categories
Content-Type: application/json

{
    "name": "categoria test",
    "description": "5"
}